### ISSUE TITLE
 search_one_direction function

### ISSUE THREAD

**Issue by DanniLi36** [BubblyYi/Coronary-Artery-Tracking-via-3D-CNN-Classification#14]
Hi,

I have ran vessels_tree_infer.py and found something wrong with the  search_one_direction in build_vessel_tree.py. 
Condition of the while loop keep unchanged so that's an infinite loop and cannot run a result. How to solve the problem? Thank you.

![image](https://user-images.githubusercontent.com/83796854/117387027-9cd2c000-af1a-11eb-8f85-f62c79f1ef96.png)

**Comment by DanniLi36** [comment]
In line 194, since 'start' is unchanged, so 'result' is also unchanged. Following variables are also unchanged (prob_mean). I suppose that 'move_direction' and 'next_point' will change, but the **move** function just always give the same output. Thus, 'find_node_initial' is always None. The while loop thus infinite.

**Comment by seekincs** [comment]
> In line 194, since 'start' is unchanged, so 'result' is also unchanged. Following variables are also unchanged (prob_mean). I suppose that 'move_direction' and 'next_point' will change, but the **move** function just always give the same output. Thus, 'find_node_initial' is always None. The while loop thus infinite.

Yes, this problem does exist, you need to update the start variable.

![image](https://user-images.githubusercontent.com/42036440/122375289-aa597c00-cf95-11eb-8f3b-a785597a25cd.png)

**Comment by BubblyYi** [comment]
Hi DanniLi36 and seekincs
Thank you for pointing out this problem. I have updated the code to fix this problem. Please update to the latest version and try again. https://github.com/BubblyYi/Coronary-Artery-Tracking-via-3D-CNN-Classification/blob/280b98c0025e474f9a403bc89f3f7cf2fe328dbd/infer_tools_tree/build_vessel_tree.py#L202
