### ISSUE TITLE
Problem about dataset format

### ISSUE THREAD

**Issue by wxqTS** [BubblyYi/Coronary-Artery-Tracking-via-3D-CNN-Classification#3]
I have concat to Dr.Theo van Walsum for dataset support, but I failed.
could someone tell me some CTA08 dataset info ? which can help me make my own dataset.

what is the 'reference.txt' in each data tells about???

Thank you very mach!

**Comment by BubblyYi** [comment]
> I have concat to Dr.Theo van Walsum for dataset support, but I failed.
> could someone tell me some CTA08 dataset info ? which can help me make my own dataset.
> 
> what is the 'reference.txt' in each data tells about???
> 
> Thank you very mach!

Hi,

please check this web link: http://coronary.bigr.nl/centerlines/about.php#submissionformat for more dataset info

**Comment by wxqTS** [comment]
> > I have concat to Dr.Theo van Walsum for dataset support, but I failed.
> > could someone tell me some CTA08 dataset info ? which can help me make my own dataset.
> > what is the 'reference.txt' in each data tells about???
> > Thank you very mach!
> 
> Hi,
> 
> please check this web link: http://coronary.bigr.nl/centerlines/about.php#submissionformat for more dataset info

Thank you for help！
