### ISSUE TITLE
I found one code line missing in function search_one_direction of infer_tools_tree/build_vessel_tree.py.

### ISSUE THREAD

**Issue by YouJiYun** [BubblyYi/Coronary-Artery-Tracking-via-3D-CNN-Classification#4]
![image](https://user-images.githubusercontent.com/36957239/91929879-f6db1000-ed11-11ea-86c9-cfee8d5b1b68.png)
I found one code line missing in function search_one_direction of infer_tools_tree/build_vessel_tree.py.
`start = next_point`

**Comment by simi-chen** [comment]
May I ask if the predicted effect is accurate? Can you provide the model you have trained？

**Comment by zyx3216825** [comment]
可以帮忙提供一下cta08数据的下载吗
