### ISSUE TITLE
Divide the data set

### ISSUE THREAD

**Issue by lalalala123456789** [BubblyYi/Coronary-Artery-Tracking-via-3D-CNN-Classification#7]
I don't know how to divide the data set,Can I have a look at your code about dividing the data set?

**Comment by deepzlk** [comment]
can i get dataset from you.Thank you very much

**Comment by zyx3216825** [comment]
> can i get dataset from you.Thank you very much

Do you have CTA08 dataset, I can't donwload it

**Comment by zyx3216825** [comment]
> I don't know how to divide the data set,Can I have a look at your code about dividing the data set?

Do you have CTA08 dataset, I can't donwload it
